version: '3'
services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
